require 'plugin_config.lsp'
require 'plugin_config.cmp'
-- require 'plugin_config.completions' (Nvim Cmp)
require 'plugin_config.lualine'
require 'plugin_config.telescope'
require 'plugin_config.bufdel'
require 'plugin_config.treesitter'
require 'plugin_config.triptych'
require 'plugin_config.mini'
require 'plugin_config.alpha'
require 'plugin_config.colorhighlights'
require 'plugin_config.scrollbar'
require 'plugin_config.virtcolumn'
