require('mini.indentscope').setup()
require('mini.trailspace').setup()
require('mini.comment').setup()
-- require('mini.animate').setup()
-- require('mini.bufremove').setup()
require('mini.surround').setup()
require('mini.pairs').setup()
