-- require 'theme_config.onedark'
-- require 'theme_config.bluloco'
-- require 'theme_config.catppuccin'
-- require 'theme_config.rosepine'
-- require 'theme_config.kanagawa'
-- require 'theme_config.nightcity'
-- require 'theme_config.ayu'
require 'theme_config.theme'
